import './globals.css';
import {Inter} from 'next/font/google';
import Link from 'next/link';
import {clsx} from 'clsx';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--inter-font',
});

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/dracula-prism/dist/css/dracula-prism.css"
        ></link>
      </head>
      <body className={clsx(inter.variable, 'bg-slate-900')}>
        <main className="max-w-xl mx-auto bg-slate-900">
          {/* <Header /> */}
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}

const Header = () => {
  return (
    <div className="py-4 flex justify-between">
      <Link href="/" className="flex flex-col">
        <span className="font-xs text-white">Alex Pate</span>
        <span className="font-xs text-white/40">Milan, Italy</span>
      </Link>
      <nav className="flex gap-4 text-white/70">
        <Link href="/" className="font-normal text-lg">
          Home
        </Link>
        <Link href="/profile" className="font-normal text-lg">
          Profile
        </Link>
        <Link href="/posts" className="font-normal text-lg">
          Writing
        </Link>
      </nav>
    </div>
  );
};

const Footer = () => {
  return (
    <footer className="flex justify-between border-t border-gray-200 mt-10 py-4">
      <nav className="flex gap-4">
        <Link href="/" className="font-medium text-lg">
          Home
        </Link>
        <Link href="/profile" className="font-medium text-lg">
          Profile
        </Link>
        <Link href="/posts" className="font-medium text-lg">
          Writing
        </Link>
      </nav>
      <div className="flex gap-4">
        <Link
          className="font-medium text-lg"
          href="https://twitter.com/alexjpate"
        >
          Twitter
        </Link>
        <Link
          className="font-medium text-lg"
          href="https://www.linkedin.com/in/alexjpate"
        >
          LinkedIn
        </Link>
      </div>
    </footer>
  );
};
